Create categories CRUD
Leoruwer/expenses-manager-api pull request #18
Opened 2022-12-02 17:11 UTC by Leoruwer

Solves #11

2022-12-13 20:36 UTC, lukzgois requested changes

2022-12-13 20:36 UTC, lukzgois commented on app/controllers/categories_controller.rb
> +    @category = Category.find_by!(slug: params[:slug])
Nesse caso estamos recuperando uma categoria unicamente pelo seu slug, o que pode levar a brechas de segurança. Se um slug válido for passado, mas a conta pertencer a outro usuário, ela será retornada normalmente.
Precisamos garantir que esse cenário não aconteça.

2022-12-13 20:36 UTC, lukzgois commented on app/models/category.rb
> +  def slugify_user
Precisamos mudar o nome desse método pois não é mais relativo ao user. Para um próximo PR, podemos pensar em tornar esse método mais genérico e move-lo para uma classe pai, ja que todos os models do sistema irão utilizá-lo.

2022-12-13 20:36 UTC, lukzgois commented on spec/controllers/categories_controller_spec.rb
> +    describe '#update' do
Aqui poderiamos adicionar um teste para garantir que a validaçao do name esta funcionando.

2022-12-13 20:36 UTC, lukzgois commented on spec/controllers/categories_controller_spec.rb
> +    describe '#destroy' do
Aqui poderiamos adicionar um teste para garantir que nao é possível excluir uma categoria de outro usuário.

2023-01-13 14:02 UTC, lukzgois requested changes

2023-01-13 14:02 UTC, lukzgois commented on app/models/category.rb
> +  validates :name, presence: true
Aqui tambem podemos adicionar um `uniqueness` usando um scope: https://guides.rubyonrails.org/active_record_validations.html#uniqueness

2023-02-02 16:50 UTC, lukzgois requested changes

2023-02-02 16:50 UTC, lukzgois commented on config/environments/production.rb
> +  config.log_formatter = Logger::Formatter.new
Isso estava gerando algum erro ou tem alguma relaçao com o PR?

2023-02-02 16:50 UTC, lukzgois commented on spec/controllers/categories_controller_spec.rb
> +  let(:another_category) { create(:category, name: 'Category') }
O nome dessa categoria esta sendo usado em algum momento? Caso contrario, podemos remove-lo.

2023-02-02 16:50 UTC, lukzgois commented on spec/models/account_spec.rb
> +        account = described_class.new(name: 'Account', user: current_user)
Quando houve essas alteraçoes em arquivos que nao necessariamente estao no contexto da feature, prefiro que seja aberto um outro PR, mesmo que pequeno, pois fica melhor para entendimento e review.

2023-02-02 17:22 UTC, Leoruwer commented on config/environments/production.rb
> +  config.log_formatter = Logger::Formatter.new
O Rubocop apontou esse erro

2023-02-03 13:45 UTC, ricardoruwer commented on spec/models/category_spec.rb
> +  describe 'model validations' do
Lá em cima tem um context "with valid params" então acho que isso aqui poderia seria um:
```suggestion
  context 'with invalid params' do
```

Daí esse último teste `it 'is valid when another user has category with same name'` vc move pro context de cima

2023-02-03 13:49 UTC, ricardoruwer commented on spec/controllers/categories_controller_spec.rb
> +    end
Se quiser deixar em 1 linha só:
```suggestion
    let(:params) { { name: name } }
```

2023-02-03 13:51 UTC, ricardoruwer approved these changes

2023-02-07 13:08 UTC, lukzgois approved these changes

2023-02-10 13:17 UTC, merged