Create defaut bills CRUD
Leoruwer/expenses-manager-api pull request #21
Opened 2022-12-05 13:38 UTC by Leoruwer

2022-12-05 14:40 UTC, ricardoruwer commented on app/controllers/default_bills_controller.rb
> +  before_action :find_default_bill, except: %i[index create]
Eu geralmente não gosto de usar esses `before_action` porque acho que fica um pouco confuso de entender o que tá acontecendo... E tbm um pouco mais difícil de manter o código futuramente...

Com o `authorize_request` eu acho que tudo bem, porque é um código que vai aplicar pra todos os métodos, de autorização da request, mas para os find's eu colocaria isso dentro do próprio método mesmo.

Ou seja, eu prefiro que seja assim:

```rb
def index
  default_bills = DefaultBill.where(user_id: find_user.id).all

  render json: default_bills, status: :ok
end
```

E aí eu até renomearia o método `find_user` para `current_user` talvez

Não é que usar esses `before_action` seja errado, ou ruim (ainda), mas pensando que esse projeto possa crescer, futuramente esses `before_action` deixam o código mais complexo, com mais indireção, e mais difícil de entender...

Mas tem vários devs que gostam de usar isso, talvez porque eles ainda não tenham sofrido como eu já sofri pra entender alguns códigos em projetos grandes 😂

2022-12-05 14:42 UTC, ricardoruwer commented on app/controllers/default_bills_controller.rb
> +    )
```suggestion
    params.permit(:name, :value)
```

🎨

2022-12-05 16:35 UTC, ricardoruwer commented on spec/controllers/default_bills_controller_spec.rb
> +    end
Isso aqui vc não tá usando em lugar nenhum, acho que vc poderia usar `let!` (com `!`) e daí vc arruma o primeiro teste do `#index` que vai começar a retornar 2 resultados ao invés de 1

2022-12-05 16:48 UTC, ricardoruwer commented on app/controllers/default_bills_controller.rb
> +  end
E aqui inclusive dá pra vc usar um memoization, não?

```suggestion
  def current_user
    @current_user ||= User.find(params[:user_id])
  rescue ActiveRecord::RecordNotFound
    render json: { errors: 'User not found' }, status: :not_found
  end
```

Porque daí se vc chamar `current_user` mais de uma vez, ele só vai fazer 1 request no banco de dados

2022-12-05 16:57 UTC, ricardoruwer commented on app/controllers/default_bills_controller.rb
> +    render json: default_bills, status: :ok
Aqui tbm pode ter um problema de segurança, o mais seguro seria usar tipo:
```suggestion
    render json: current_user.default_bills, status: :ok
```

2022-12-05 17:03 UTC, ricardoruwer commented on app/controllers/default_bills_controller.rb
> +    @default_bill = DefaultBill.find_by!(slug: params[:slug])
Aqui vc conseguiria pegar uma `DefaultBill` de outro usuário, se vc descobrir qual é o slug dele. Então acho que o correto seria:
```suggestion
    @default_bill ||= current_user.default_bills.find_by!(slug: params[:slug])
```

2022-12-05 17:03 UTC, ricardoruwer commented on app/controllers/default_bills_controller.rb
> +    new_default_bill = DefaultBill.new(default_bill_params)
```suggestion
    new_default_bill = current_user.default_bills.new(default_bill_params)
```

2022-12-05 17:05 UTC, ricardoruwer commented on app/controllers/default_bills_controller.rb
> +    @user = User.find(params[:user_id])
Vc tem que ter um jeito de pegar o `user` pelo JWT token ao invés de passar o `user_id` nos params

2022-12-05 17:18 UTC, ricardoruwer commented on app/controllers/default_bills_controller.rb
> +    @user = User.find(params[:user_id])
Vc pode usar o `authorize_request` para isso, no ApplicationController

2022-12-06 11:58 UTC, Leoruwer commented on spec/controllers/default_bills_controller_spec.rb
> +    end
Na verdade a intenção é essa, já que essa segunda conta é de outro usuário, e no #index eu puxo as contas do `current_user`, e checo se essa conta não aparece lá

2022-12-06 13:33 UTC, ricardoruwer commented on app/controllers/application_controller.rb
> +      @current_user = User.find(decoded[:user_id])
Eu não sei te explicar exatamente, mas não é comum as pessoas setarem essas variáveis de classe (com `@`) no ApplicationController pra usar nos outros Controllers. E a grande maioria das vezes usam isso só no método `initialize` ou pra fazer `memoization`.

Então eu sugeriria vc fazer alguma parada tipo assim, talvez:
```rb
def authorize_request
  current_user.present?
rescue ActiveRecord::RecordNotFound, JWT::DecodeError => e
  render json: { message: "Unauthorized" }, status: :unauthorized
end

def current_user
  @current_user ||= User.find(decoded_token[:user_id])
end

private

def decoded_token
  header = request.headers['Authorization']
  header = header.split.last if header
  JsonWebToken.decode(header)
end
```

E aí lá no DefaultBillsController vc usa o `before_action :authorize_request` pra garantir que o usuário precisa estar logado pra acessar esses endpoints e ao invés de usar `@current_user` vc usa só `current_user`

Algo assim... não testei esse código pra ver se funciona tbm

2022-12-06 13:36 UTC, ricardoruwer commented on app/controllers/application_controller.rb
>        render json: { errors: e.message }, status: :unauthorized
Aqui vc mostra um JSON com a mensagem de erro para quem tá tentando acessar esse endpoint, né? Esse erro não tá mostrando nenhuma mensagem sensível?
Talvez vc nem precisa renderizar esse `e.message`, e só mostra uma mensagem padrão, e se quiser dá pra meter um log pra vc conseguir consultar depois:
```rb
  Rails.logger.warn("Unauthorized user trying to log in: #{e.message}")
  render json: { message: "Unauthorized" }, status: :unauthorized
```

Mas aqui é só um questionamento mesmo, só pra vc ficar esperto de olhar essas coisas sempre :)

2022-12-06 13:54 UTC, ricardoruwer commented on spec/controllers/default_bills_controller_spec.rb
> +    end
Entendi, mas mesmo assim, essa conta `second_default_bill` nunca é criada no banco de dados.

Vc precisa trocar para:
```suggestion
    let!(:second_default_bill) do
      create(:default_bill, name: 'Second default bill', slug: 'second-default_bill-2', user_id: another_user.id)
    end
```

Pq daí sim essa default_bill vai ser criada no banco de dados e o seu teste vai fazer sentido

2022-12-06 14:00 UTC, ricardoruwer commented on spec/controllers/default_bills_controller_spec.rb
> +        json = JSON.parse(response.body)
Se vc quiser, dá pra jogar todos esses `JSON.parse(response.body)` pra dentro de um `let`, já que vc repete ele em todos os testes

```rb
let(:json) { JSON.parse(response.body) }
```

2022-12-06 14:11 UTC, ricardoruwer commented on app/controllers/default_bills_controller.rb
> +  before_action :find_default_bill, except: %i[index create]
Eu faria essas alterações aqui tbm:

1. Remover essa linha 5
2. Renomear o método `find_default_bill` para `default_bill`
3. Renomear todos lugares que usam `@default_bill` para `default_bill`

Acho que o resultado vai ser o mesmo, e o código vai ficar mais limpo :)

2022-12-08 19:30 UTC, ricardoruwer commented on app/controllers/default_bills_controller.rb
> +  before_action :authorize_request
Se vc não tiver nenhum endpoint público nessa sua app, dá pra considerar mover essa linha pra dentro do `ApplicationController` tbm, né? #fikdik

2022-12-08 19:31 UTC, ricardoruwer approved these changes
TOP

2022-12-15 17:05 UTC, Leoruwer commented on app/controllers/default_bills_controller.rb
> +  before_action :authorize_request
Há somente um Endpoint público, que é para Login

2022-12-16 15:11 UTC, ricardoruwer commented on app/models/application_record.rb
> +  after_initialize :slugify_name
Gostei da ideia de vc pensar em colocar isso aqui já que é algo usado em todos os models, e agora ele faz sentido porque agora todos os models tem um slug, mas se a gente for pensar que no futuro possivelmente iremos criar algum model que não tenha slug, aí esse código vai dar uma atrapalhada no rolê 😄 

Então o que eu faria é manter esse método `slugify_name` aqui, mas jogar esse `after_initialize` pra dentro de todos os models que precisam dele.

2022-12-16 15:16 UTC, ricardoruwer commented on spec/models/default_bill_spec.rb
> +    expect(default_bill.slug).not_to be_nil
Também daria pra fazer tipo:

```suggestion
    expect(default_bill.slug).to match(/default-bill-.*/)
```

Acho que isso funciona... Tem que testar 😆

2022-12-16 15:24 UTC, ricardoruwer commented on app/models/application_record.rb
> +  after_initialize :slugify_name
Se bem que no método `slugify_name` vc depende que todos os models também tenham um atributo `name`. Ou seja, com esse código aqui, vc bota uma dependência de que todos os seus models tenham `slug` e `name`, né?

Então talvez pra evitar de duplicar muito código, o que eu faria seria, talvez, algo assim:

No model DefaultBill:
```rb
after_initialize :slugify_name

private

def slugify_name
  slugify(name)
end
```

E aqui no ApplicationRecord:
```rb
protected

def slugify(value)
  self.slug = "#{value}-#{SecureRandom.hex(3)}".downcase.parameterize if value.present?
end
```

Algo assim... não consegui pensar em nada melhor agora 😅

2022-12-16 19:23 UTC, lukzgois requested changes

2022-12-16 19:23 UTC, lukzgois commented on spec/controllers/default_bills_controller_spec.rb
> +  describe '#show' do
Acho que seria interessante adicionar uma spec quando o slug é válido, mas pertence a outro usuário

2022-12-16 19:23 UTC, lukzgois commented on spec/controllers/default_bills_controller_spec.rb
> +  describe '#update' do
Também seria interessante adicionar uma spec para garantir que não é possível alterar um registro de outro usuário.

2022-12-16 19:23 UTC, lukzgois commented on spec/controllers/default_bills_controller_spec.rb
> +  describe '#update' do
Tambem seria bom ter specs para as validaçoes aqui.

2022-12-16 19:23 UTC, lukzgois commented on spec/controllers/default_bills_controller_spec.rb
> +  describe '#destroy' do
Poderiamos tambem adicionar um caso de uso para garantir que nao eh possivel excluir o registro de outro usuario.

2022-12-16 19:23 UTC, lukzgois commented on spec/factories/default_bills.rb
> +FactoryBot.define do
Poderiamos utilizar a biblioteca faker para a criaçao das factories.

2022-12-16 19:23 UTC, lukzgois commented on spec/models/default_bill_spec.rb
> +RSpec.describe DefaultBill do
Seria bom adicionar um teste para as validaçoes do model

2022-12-16 19:23 UTC, lukzgois commented on spec/factories/default_bills.rb
> +FactoryBot.define do
Tambem poderiamos criar as associaçoes diretamente pela factory: https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md#associations

2022-12-16 19:23 UTC, lukzgois commented on spec/controllers/default_bills_controller_spec.rb
> +    context 'when JWT Token is invalid' do
Poderiamos mover essas specs que verificam o JWT token invalido para um shared example:

https://relishapp.com/rspec/rspec-core/docs/example-groups/shared-examples
https://railsware.com/blog/using-configurable-shared-examples-in-rspec/

2022-12-22 14:21 UTC, lukzgois requested changes

2022-12-22 14:21 UTC, lukzgois commented on app/models/default_bill.rb
> +class DefaultBill < ApplicationRecord
Para esse model poderiamos utilizar a gem [money-rails](https://github.com/RubyMoney/money-rails) para nos ajudar a lidar com os valores monetarios.

2022-12-22 14:21 UTC, lukzgois commented on db/migrate/20221205125856_create_default_bills.rb
> +      t.integer :value, nil: true
Nao sei como me sinto a respeito do valor nulo para o campo `value`. Acho que seria interessante que esse campo tivesse um valor quando fosse cadastrado, se nao, qual o sentido de ter uma conta padrao criada todos os meses? O que voce acha?

2022-12-22 14:21 UTC, lukzgois commented on db/migrate/20221205125856_create_default_bills.rb
> +      t.integer :value, nil: true
No caso de mudarmos esse campo para obrigatorio, teriamos que adicionar tambem uma validacao para que ele fosse maior que 0 sempre.

2022-12-23 18:12 UTC, ricardoruwer commented on db/migrate/20221205125856_create_default_bills.rb
> +      t.integer :value, nil: true
Vc vai salvar esse valor em centavos? (porque tá como integer) 
Pq daí acho que seria legal renomear esse campo para `value_in_cents` tbm

2022-12-23 18:14 UTC, ricardoruwer commented on app/models/default_bill.rb
> +class DefaultBill < ApplicationRecord
Eu não diria que é exatamente necessário para uma app que só vai gerenciar algumas contas, mas talvez seja legal pra vc aprender 😄 pq mexer com esses valores monetários sempre é meio zica

2022-12-23 18:23 UTC, ricardoruwer commented on spec/controllers/default_bills_controller_spec.rb
> +    context 'when JWT Token is invalid' do
Eu sempre só tive más experiências com shared examples na minha vida e sempre tento evitar ao máximo de usar, mas tem gente que gosta... Então, sobre usar shared examples:

**Prós:**
- Vc aprender como funciona pq provavelmente vc vai encontrar isso em alguma app algum dia e vai precisar dar alguma manutenção nisso, principalmente pq essa parte do código vai ser bem difícil de entender, com muita indireção e confusa 😄 

**Contras:**
- É uma merda

Aí eu, pra evitar de usar ele, talvez eu jogaria esse teste pra dentro de um `application_controller_spec.rb` e não precisaria ficar repetindo ele em vários specs diferentes

Mas, né, como essa app é pra vc estudar e aprender, até incentivo que vc use os shared examples mesmo

2022-12-28 14:13 UTC, Leoruwer commented on db/migrate/20221205125856_create_default_bills.rb
> +      t.integer :value, nil: true
Oque eu aprendi é sempre salvar o valor monetário em centavos usando Integer, então a ideia é sim salvar em centavos, talvez mudar o nome para `value_in_cents` fique melhor

Já sobre existir a possibilidade dele ser nulo, é algo que eu tenho no meu projeto original, algumas contas que tem todo mês, como por exemplo, Energia ou Condominio, mas que não são os mesmos valores todo mês, então eu acabo criando eles sem valores, e no final do mês na hora que vou pagar as contas, eu cadastro o valor dela

2023-01-04 14:47 UTC, lukzgois approved these changes

2023-01-04 17:39 UTC, merged