Add JWT Token validation
Leoruwer/expenses-manager-api pull request #5
Opened 2022-10-13 18:24 UTC by Leoruwer

2022-11-01 13:44 UTC, lukzgois requested changes

2022-11-01 13:44 UTC, lukzgois commented on config/routes.rb
> +      get '/*a', to: 'application#not_found'
Para que essa rota com `/*a`?

2022-11-01 13:44 UTC, lukzgois commented on app/controllers/application_controller.rb
> +      @current_user = User.find(@decoded[:user_id])
Nesse caso aqui nao precisariamos declarar com o `@`, pois sao variaveis locais. Nao necessitamos delas em outros metodos da classe.

2022-11-01 13:44 UTC, lukzgois commented on app/controllers/api/v1/authentication_controller.rb
> +    @user = User.find_by_email(params[:email])
Nesse caso aqui nao precisariamos declarar com o `@`, pois sao variaveis locais. Nao necessitamos delas em outros metodos da classe.

2022-11-01 13:44 UTC, lukzgois commented on app/controllers/api/v1/authentication_controller.rb
> +    if @user&.authenticate(params[:password])
Esset método `authenticate` já existe?

2022-11-18 17:19 UTC, Leoruwer commented on config/routes.rb
> +      get '/*a', to: 'application#not_found'
Acabei removendo esse rota nesse [PR](https://github.com/Leoruwer/expenses-manager-api/pull/6)

2022-11-18 17:25 UTC, Leoruwer commented on app/controllers/api/v1/authentication_controller.rb
> +    if @user&.authenticate(params[:password])
Esse método é adicionado junto ao `has_secure_password` feito aqui nesse [PR](https://github.com/Leoruwer/expenses-manager-api/pull/6/files#diff-9802ca3c9c4cf89904fd44bc114e35ebdf2c5dd3d5b645491e2b253e1afef29bR2)

https://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html

2022-11-18 20:06 UTC, lukzgois requested changes

2022-11-18 20:06 UTC, lukzgois commented on app/controllers/api/v1/authentication_controller.rb
> +      time = Time.now + 24.hours.to_i
Acho que aqui poderia utilizar diretamente o metodo para tempo presente na classe, como foi usado aqui: https://github.com/Leoruwer/expenses-manager-api/pull/5/files#diff-0f2aab374a38d4b7c0f68ca6d915f0a2621701a96853490414fd22adb5c221c3R4

2022-11-24 13:26 UTC, lukzgois approved these changes

2022-11-24 17:40 UTC, merged

2023-01-04 17:39 UTC, adbatista reviewed
faltaram testes

2023-01-04 17:39 UTC, adbatista commented on app/controllers/api/v1/authentication_controller.rb
> +  before_action :authorize_request, except: :login
pq isso se ta dando except na unica action que tem nesse controller?

2023-01-04 17:39 UTC, adbatista commented on app/controllers/application_controller.rb
> +  end
nao ta chamando em lugar nenhum

2023-01-04 17:39 UTC, adbatista commented on app/controllers/application_controller.rb
> +    header = header.split(' ').last if header
o rails ja tem um helper que faz isso authenticate_with_http_token

2023-01-04 17:39 UTC, adbatista commented on app/controllers/application_controller.rb
> +      render json: { errors: e.message }, status: :unauthorized
se o código é o mesmo, o que muda é as exception, da pra usar um rescue só com ambas exceptions

2023-01-04 17:39 UTC, adbatista commented on app/models/json_web_token.rb
> +end
aqui ta ok, mas não está em uma abordagem OOP daria para reorganizar melhor