Make User CRUD and authentication with JWT
Leoruwer/expenses-manager-api pull request #6
Opened 2022-10-18 12:42 UTC by Leoruwer

Could't keep the column name as `type`, since it's an inheritance_column
[Saw it here](https://stackoverflow.com/questions/17879024/activerecordsubclassnotfound-the-single-table-inheritance-mechanism-failed-to)

2022-11-01 13:53 UTC, lukzgois requested changes

2022-11-01 13:53 UTC, lukzgois commented on app/controllers/users_controller.rb
> +    @user = User.find_by_username!(params[:username])
Nesse caso, acho que poderiamos retirar a coluna `username` e manter apenas a coluna `email`, uma vez que ela já é única no banco de dados. O que vc acha?

2022-11-01 13:53 UTC, lukzgois commented on app/controllers/users_controller.rb
> +  before_action :authorize_request, except: :create
Acho que podemos manter todos os endpoints do CRUD de usuários necessitando de autenticaçao, ja que esses endpoints serao utilizados apenas por admins. Para a criaçao de novos usuarios, podemos utilizar um endpoint extra, algo como `/register`, e mante-lo em um controller separado para deixar mais organizaado.

2022-11-01 13:53 UTC, lukzgois commented on app/controllers/users_controller.rb
> +      :name, :username, :email, :password, :password_confirmation, :type
Foi esquecido de mudar o campo para `role` aqui.

2022-11-18 20:13 UTC, lukzgois requested changes

2022-11-18 20:13 UTC, lukzgois commented on db/migrate/20221118171410_remove_field_username_from_users.rb
> +class RemoveFieldUsernameFromUsers < ActiveRecord::Migration[7.0]
Nesse caso aqui nao seria necessario essa migration, poderiamos apenas alterar a migration original e deixá-la sem o campo `username`, uma vez que ela esta sendo criada nesse mesmo PR.

2022-11-18 20:13 UTC, lukzgois commented on app/controllers/admin/users_controller.rb
> +    @users = User.all
Nesse caso, `users` nao precisa ser uma variavel de classe, ja que esta sendo usado apenas nesse metodo.

2022-11-18 20:13 UTC, lukzgois commented on app/controllers/admin/users_controller.rb
> +    @user = User.new(user_params)
Acho que podemos chamar essa variavel de `new_user`, para nao confundir com a variavel de classe `@user`. O `new_user` tambem nao necessita ser uma variavel de classe.

2022-11-18 20:13 UTC, lukzgois commented on app/controllers/users_controller.rb
> +    @user = User.new(user_params)
Mesma coisa aqui com a variavel de classe. Tomar mais cuidado com esse detalhe, deixar apenas como variavel de classe as que serao utilizadas em outros metodos ou passadas para views.

2022-11-24 13:28 UTC, lukzgois approved these changes

2022-11-24 17:41 UTC, merged

2023-01-04 17:41 UTC, adbatista reviewed
specs

2023-01-04 17:41 UTC, adbatista commented on app/controllers/admin/users_controller.rb
> +    render json: users, status: :ok
ok ja é retorno default nao precisa dele aqui

2023-01-04 17:41 UTC, adbatista commented on app/controllers/admin/users_controller.rb
> +    end
e quando o update falha, o que acontece?

2023-01-04 17:41 UTC, adbatista commented on app/controllers/admin/users_controller.rb
> +    @user.destroy
e quando destroi? nao redireciona nem renderiza nada?