Add user_controller tests
Leoruwer/expenses-manager-api pull request #7
Opened 2022-10-25 13:37 UTC by Leoruwer

This changes includes:
- Add rspec_rails
- Add factory_bot_rails
- Bug-fixes on user_controller
- Improved uniqueness for User
- New index for user_table
- Tests for user_controller

2022-11-01 14:08 UTC, lukzgois requested changes
Os testes estao bons, contudo, estao muito "inchados" por nao utilizar muitos blocos `let` e `subject`. Acho que podemos utilizar mais esse tipo de estrategia para diminuir a duplicaçao de codigo e deixar os testes mais "enxutos".

Recomendo esse artigo como guia: https://benscheirman.com/2011/05/dry-up-your-rspec-files-with-subject-let-blocks/

2022-11-22 19:31 UTC, ricardoruwer commented on .github/workflows/github-actions.yml
> +name: GitHub Actions
Só pra aprendizado: acho que isso aqui poderia estar em um PR separado

2022-11-22 19:32 UTC, ricardoruwer commented on Gemfile
> +gem 'rspec-rails', '~> 6.0', '>= 6.0.1'
Acho que tbm seria legal um PR separado só colocando essas gems

2022-11-22 19:32 UTC, ricardoruwer commented on Gemfile
> +gem 'rspec-rails', '~> 6.0', '>= 6.0.1'
Só pra não ficar um PR grande igual esse, e ruim de revisar

2022-11-22 19:34 UTC, ricardoruwer commented on app/controllers/admin/users_controller.rb
> +    @user = User.find_by_slug!(params[:slug])
Esse método aqui existe? Talvez esteja deprecated? O ideal acho que seria:
```rb
@user = User.find_by!(slug: params[:slug])
```

2022-11-22 19:39 UTC, ricardoruwer commented on app/models/user.rb
> +    self.slug = "#{self.name}-#{rand(1000..9999)}"
```suggestion
    self.slug = "#{self.name}-#{rand(1000..9999)}".downcase.parameterize
```

2022-11-22 19:42 UTC, ricardoruwer commented on app/models/user.rb
> +    self.slug = "#{self.name}-#{rand(1000..9999)}"
Acho que daria pra trocar esse `rand` pra alguma coisa que seja mais segura, talvez algo do tipo:
```rb
SecureRandom.hex(3)
```

Daí ficaria:

```suggestion
    self.slug = "#{self.name}-#{SecureRandom.hex(3)}".downcase.parameterize
```

2022-11-22 19:50 UTC, ricardoruwer commented on spec/controllers/admin/users_controller_spec.rb
> +  context 'when JWT Token is invalid' do
Quando eu tava lendo seus testes eu pensei: "podia ter um teste validando se o JWT token é inválido" daí eu tive que descer toda a rolagem pra ver que vc fez um teste pra isso...

O mais comum é colocar esses testes dentro do describe que vc fez lá em cima... Tipo, vc ter só um `describe "#index"` no seu arquivo de testes... Aqui vc tem 2...

Por exemplo:
```rb
describe '#index' do
  subject { get(admin_users_path, headers: {'Authorization': jwt_token}) }

  it 'returns all users' do
    subject

    json = JSON.parse(response.body)

    expect(response).to have_http_status :ok
    expect(json[0]['email']).to eq(current_user.email)
    expect(json[1]['email']).to eq(another_user.email)
  end

  context 'when JWT Token is invalid' do
    let(:jwt_token) { "invalid-token" }

    it 'returns invalid JWT token' do
      subject

      expect(response).to have_http_status :unauthorized
      expect(JSON.parse(response.body)).to include('message' => 'Invalid JWT token')
    end
  end
end
```

Entendes?

2022-11-22 19:51 UTC, ricardoruwer commented on spec/controllers/admin/users_controller_spec.rb
> +  context 'when JWT Token is invalid' do
E aí repete essa mesma ideia pra todos os outros: show, update, destroy, etc

2022-11-22 19:53 UTC, ricardoruwer commented on spec/controllers/users_controller_spec.rb
> +        it 'creates a user' do
```suggestion
        let(:role) { 'admin' }
        
        it 'creates a user' do
```

2022-11-22 19:55 UTC, ricardoruwer commented on spec/controllers/users_controller_spec.rb
> +          expect(json['errors']).to include('Password can\'t be blank')
```suggestion
          expect(json['errors']).to include("Password can't be blank")
```

2022-11-22 19:56 UTC, ricardoruwer commented on spec/controllers/users_controller_spec.rb
> +          expect(json['errors']).to include('Name can\'t be blank')
```suggestion
          expect(json['errors']).to include("Name can't be blank")
```

2022-11-22 19:57 UTC, ricardoruwer commented on spec/controllers/users_controller_spec.rb
> +    end
Acho que vc pode usar assim já que, pelo que eu vi, vc não usa essas outras variáveis em lugar nenhum

```suggestion
    let(:params) do
      {
        name: 'Foo Bar',
        email: 'foobar@mail.com',
        password: 'securepassword123',
        password_confirmation: password,
        role: 'user'
      }
    end
```

2022-11-22 19:58 UTC, ricardoruwer commented on spec/controllers/users_controller_spec.rb
> +          expect(json['errors']).to include('Email can\'t be blank')
```suggestion
          expect(json['errors']).to include("Email can't be blank")
```

2022-11-22 20:40 UTC, Leoruwer commented on app/controllers/admin/users_controller.rb
> +    @user = User.find_by_slug!(params[:slug])
Esses `find_by_...` dinâmicos não foram depreciados
`All dynamic methods except for find_by_... and find_by_...! are deprecated.`
https://edgeguides.rubyonrails.org/4_0_release_notes.html#active-record-deprecations

2022-11-23 14:07 UTC, ricardoruwer commented on app/controllers/admin/users_controller.rb
> +    @user = User.find_by_slug!(params[:slug])
Ainda assim prefiro o `find_by!` pra manter um padrão, mas beleza...

2022-11-24 13:39 UTC, lukzgois requested changes
o PR esta ok para mim agora, soh acho melhor retirar essa parte do github actions para outro PR

2022-11-25 11:41 UTC, Leoruwer commented on spec/controllers/users_controller_spec.rb
> +    end
`name` uso na linha [78](https://github.com/Leoruwer/expenses-manager-api/pull/7/files#diff-5f44c1c580dbc94788e40f1aecf6f711215f30ce917214dc8d25765105cc4a37R78)
`password` uso na linha [91](https://github.com/Leoruwer/expenses-manager-api/pull/7/files#diff-5f44c1c580dbc94788e40f1aecf6f711215f30ce917214dc8d25765105cc4a37R91)
`email` uso na linha [52](https://github.com/Leoruwer/expenses-manager-api/pull/7/files#diff-5f44c1c580dbc94788e40f1aecf6f711215f30ce917214dc8d25765105cc4a37R52)
`role` uso na linha [37](https://github.com/Leoruwer/expenses-manager-api/pull/7/files#diff-5f44c1c580dbc94788e40f1aecf6f711215f30ce917214dc8d25765105cc4a37R37)

2022-11-25 13:52 UTC, lukzgois approved these changes

2022-11-25 13:52 UTC, merged

2023-01-04 17:53 UTC, adbatista reviewed
legal, só precisa treinar mais organização de testes

2023-01-04 17:53 UTC, adbatista commented on app/controllers/admin/users_controller.rb
> +    else
boa

2023-01-04 17:53 UTC, adbatista commented on app/controllers/application_controller.rb
> +      render json: { message: 'Invalid JWT token', errors: e.message }, status: :unauthorized
legal isso, mas quebra o padrado dos jsons de erro, ficando só esse com schema diferente dos demais

2023-01-04 17:53 UTC, adbatista commented on app/models/user.rb
> +  after_initialize :slugify_user
aqui da problema vai ser chamado toda vez que o objeto é instanciado

2023-01-04 17:53 UTC, adbatista commented on app/models/user.rb
> +    self.slug = "#{self.name}-#{SecureRandom.hex(3)}".downcase.parameterize
nao precisa do self no name

2023-01-04 17:53 UTC, adbatista commented on db/migrate/20221018051310_create_users.rb
> +    add_index :users, :email, unique: true
nao. se edita migration depois que estiver na master, aqui ok pois nao é um projeto em produçao, mas em projeto rodando nao da pra fazer isso

2023-01-04 17:53 UTC, adbatista commented on spec/controllers/admin/users_controller_spec.rb
> +        subject
o subject é usado para o step de setup e não de exercise como está aqui, exite esse tipo de coisa que acaba atrapalhando a legibilidade do teste

2023-01-04 17:53 UTC, adbatista commented on spec/controllers/admin/users_controller_spec.rb
> +        expect(json[1]['email']).to eq(another_user.email)
aqui seria melhor, verificar toda resposta, para garantir o retorno correto, e o status ser em um teste separado